version: '3.1'

services:

  db:
    image: postgis/postgis
    restart: always
    container_name: db
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./data:/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
      - PGDATA=/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
  api:
    tty: true
    restart: on-failure
    build: .
    volumes:
      - ./src:/app/src
      - ./data:/data
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
volumes:
  db-data: