# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgis/postgis
    restart: always
    container_name: db
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./data:/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST_AUTH_METHOD=trust
      - PGDATA=/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  db-data: